//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DX_Application
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_AttendedEntities : DbContext
    {
        public db_AttendedEntities()
            : base("name=db_AttendedEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Accounts> tb_Accounts { get; set; }
        public virtual DbSet<tb_Attended> tb_Attended { get; set; }
        public virtual DbSet<tb_ClassRooms> tb_ClassRooms { get; set; }
        public virtual DbSet<tb_Courses> tb_Courses { get; set; }
        public virtual DbSet<tb_RegisterCourses> tb_RegisterCourses { get; set; }
        public virtual DbSet<tb_Students> tb_Students { get; set; }
        public virtual DbSet<tb_Teachers> tb_Teachers { get; set; }
    }
}
