//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DX_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_DiemDanh
    {
        public string col_NgayDD { get; set; }
        public string col_MaHP { get; set; }
        public string col_MaSV { get; set; }
        public string col_GhiChu { get; set; }
        public Nullable<System.TimeSpan> col_GioDD { get; set; }
    }
}
