//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DX_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_GiangVien
    {
        public string col_MaGV { get; set; }
        public string col_Khoa { get; set; }
        public string col_Email { get; set; }
        public bool col_GioiTinh { get; set; }
        public string col_HoTen { get; set; }
    }
}
