//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DX_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Accounts
    {
        public string col_UserID { get; set; }
        public string col_Password { get; set; }
        public string col_Role { get; set; }
    
        public virtual tb_Teachers tb_Teachers { get; set; }
    }
}
