//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DX_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_RegisterCourses
    {
        public int col_Index_RegisterCourses { get; set; }
        public int col_CoursesID { get; set; }
        public string col_StudentID { get; set; }
        public string col_Status { get; set; }
    
        public virtual tb_Courses tb_Courses { get; set; }
        public virtual tb_Students tb_Students { get; set; }
    }
}
