//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DX_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Students()
        {
            this.tb_Attended = new HashSet<tb_Attended>();
            this.tb_RegisterCourses = new HashSet<tb_RegisterCourses>();
        }
    
        public string col_StudentID { get; set; }
        public string col_FName { get; set; }
        public System.DateTime col_DayoBirth { get; set; }
        public string col_Major { get; set; }
        public string col_Email { get; set; }
        public string col_Phone { get; set; }
        public Nullable<bool> col_Sex { get; set; }
        public byte[] col_Avatar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Attended> tb_Attended { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_RegisterCourses> tb_RegisterCourses { get; set; }
    }
}
